spring.application.name=meeting-room-booking

spring.datasource.url=jdbc:postgresql://localhost:5432/meeting_room_booking
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change-this-secret-key-change-this-secret-key
app.jwt.expiration-ms=86400000
